[theme]
primaryColor="#575fe8"  # Color principal
backgroundColor="#f5f7f3"  # Color de fondo general
secondaryBackgroundColor="#c9eab8"  # Color de fondo secundario
textColor="#262730"  # Color del texto
